modLoader="javafml" #mandatory

loaderVersion="[31,)"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="cinderbloom" #mandatory

version="1.0.0 Alpha" #mandatory

displayName="Cinderbloom (prev. Infernal Hardship)" #mandatory

#updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/cinderbloom" #optional

logoFile="cinderbloom_logo.png"

#credits="" #optional

authors="Enderman842, Fr3nderman, Snowylagito_, mr_ch0c0late1, Sameko_Azumi, idrae_, SquidudGaming"

description='''

'''

[[dependencies.cinderbloom]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.cinderbloom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
